"""
Definition of classes for each ANPHON input block
Basic idea: For each input block all possible tags are stored in a class, where objects can be created for each input block; Most attributes are set as NONE as default
-> To be able to set each attribute individually when creating an input. Some are set by functions availabe for ase ATOM objects

Input blocks for cutoff, cell and positions are created by individual functions (below) since they do not require selection of keywords

For the kpoint block two options are availabe to get the k-points:
    via an inbuild function of ase
    via the seekpath environment


"""


from ase.io import cif
from ase.data import chemical_symbols, atomic_masses
from ase.units import Bohr

import argparse  #  to be able to set variables when calling the script
import seekpath
import spglib as spg
import sys
from ase.io.jsonio import write_json, read_json


from cif2ALM import get_fcsXML, process_additional_arguments, get_keywords_from_template

#  Since the SeeKpath package seems to use some deprecated spglib functions this line is used to suppress the "DeprecationWarnings" popping up in the console
import warnings ; warnings.warn = lambda *args,**kwargs: None



#  Function to get the cell block from an ASE atoms object, values in bohr -> this might produce some spikes in the 
def set_prim_cell_block(aseAtom, multFactor = 1, std = 'prim'):
    cell = [[multFactor]]
    
    fracCoords = aseAtom.get_scaled_positions()
    convCell = aseAtom.get_cell()
    numbers = aseAtom.get_atomic_numbers()
    
    standCell = spg.standardize_cell([convCell, fracCoords, numbers])

    primCell = spg.find_primitive(standCell)
    
    if std == 'prim':
        
        for line in primCell[0]:
            curLine = [round(a/Bohr, 10) for a in line]
            cell.append(curLine)
            
    elif std == 'crys':
        for line in standCell[0]:
            curLine = [round(a/Bohr, 10) for a in line]
            cell.append(curLine)
    
    return cell


#  class for the &general input block

class ANPHONgeneral():
    
    def __init__(self, aseAtom, **kwargs):
        
        #  List of all variables that can be set for the general block input
        #  descriptions taken from ALAMODE webpage
        self.PREFIX = kwargs.get('PREFIX', None)  #  Job prefix to be used for names of output
        self.MODE = kwargs.get('MODE', None)  #  possible options are phonons, RTA or SCPH
        self.NKD = len(set(aseAtom.numbers))  #  Number of atomic species
        #self.KD = [chemical_symbols[el] for el in set(aseAtom.numbers)]  #  Chemical symbols for each atom species
        self.KD = [chemical_symbols[el] for el in list(dict.fromkeys(aseAtom.numbers))]
        #self.MASS = [atomic_masses[el] for el in set(aseAtom.numbers)]  #  Masses for each atom species
        self.MASS = [atomic_masses[el] for el in list(dict.fromkeys(aseAtom.numbers))]
        self.FCSXML = kwargs.get('FCSXML', None)  #  XML file containing force constants generated by the program alm
        self.FC2XML = kwargs.get('FC2XML', None)  #  XML file containing harmonic force constants for different size of supercell
        self.TOLERANCE = kwargs.get('TOLERANCE', None)  #  Tolerance for finding symmetry operations
        self.PRINTSYM = kwargs.get('PRINTSYM', None)  #  if 1 Symmetry operations will be saved in “SYMM_INFO_PRIM”
        self.NONANALYTIC = kwargs.get('NONANALYTIC', None)  #  set 0,1,2,3 if 1-3 non-analytic correction included (1 damping by Parlinski, 2 mixed space approach, 3 Ewald method)
        self.NA_SIGMA = kwargs.get('NA_SIGMA', None)  #  Damping factor for the non-analytic term
        self.BORNINFO = kwargs.get('BORNINFO', None)  #  File containing the macroscopic dielectric tensor and Born effective charges for the non-analytic correction
        self.BORNSYM = kwargs.get('BORNSYM', None)  #  if 1 Symmetrize Born effective charges by using point group symmetry
        self.TMIN = kwargs.get('TMIN', None)
        self.TMAX = kwargs.get('TMAX', None)
        self.DT = kwargs.get('DT', None)  #  Temperature range and its stride in units of Kelvin
        self.EMIN = kwargs.get('EMIN', None)
        self.EMAX = kwargs.get('EMAX', None)
        self.DELTA_E = kwargs.get('DELTA_E', None)  #  Energy range and its stride in units of kayser (cm^-1)
        self.ISMEAR = kwargs.get('ISMEAR', None)  #  specifies the method for Brillouin zone integration (-1 tetrahedron, 0 Lorentzian, 1 Gaussian) with width of EPSILON
        self.EPSILON = kwargs.get('EPSILON', None)  #  Smearing width in units of Kayser (cm^-1)
        self.BCONNECT = kwargs.get('BCONNECT', None)  #  0 save phonon band without change, 1 phonon band connected via similarity of eigenvectors, 2 same as 1, but save info about connectivity
        self.CLASSICAL = kwargs.get('CLASSICAL', None)  #  0 quantum statistics, 1 classical statistics
        self.TRISYM = kwargs.get('TRISYM', None)  #  Flag to use symmetry operations to reduce the number of triples of k points for self-energy calculations
        self.RESTART = kwargs.get('RESTART', None)  #  Flag to restart the calculation when MODE = RTA
        
    def get_all_att(self):

        List = vars(self)

        return List

        
    


#  class for the scph block -> is only necessary if MODE == SCPH
class scph():
    
    def __init__(self, **kwargs):
        
        #  List of all variables that can be set for the scph block input
        #  descriptions taken from ALAMODE webpage
        
        self.KMESH_INTERPOLATE = kwargs.get('KMESH_INTERPOLATE', None)  #  In the iteration process of the SCPH equation, the interpolation is done using the k-mesh defined by KMESH_INTERPOLATE.
        self.KMESH_SCPH = kwargs.get('KMESH_SCPH', None)  #  This k-mesh is used for the inner loop of the SCPH equation. Each value of KMESH_SCPH must be equal to or a multiple of the number of KMESH_INTERPOLATE in the same direction.
        self.SELF_OFFDIAG = kwargs.get('SELF_OFFDIAG', None)  #  if 1 Consider the off-diagonal elements of the loop diagram in the SCPH calculation
        self.TOL_SCPH = kwargs.get('TOL_SCPH', None)  #  Stopping criterion of the SCPH iteration
        self.MIXALPHA = kwargs.get('MIXALPHA', None)  #  Mixing parameter used in the SCPH iteration
        self.MAXITER = kwargs.get('MAXITER', None)  #  Maximum number of the SCPH iteration
        self.LOWER_TEMP = kwargs.get('LOWER_TEMP', None)  #  if 0 SCPH from t_min to t_max, if 1 vice versa
        self.WARMSTART = kwargs.get('WARMSTART', None)  #  if 0 initialize SCPH by harmonic frequencies and eigenvectors, if 1 initialize by solution of prev. temperature
        self.IALGO = kwargs.get('IALGO', None)  #  MPI parallelization for 0 k-point, 1 phonon branch
        self.RESTART_SCPH = kwargs.get('RESTART_SCPH', None)  #  if 1 restart SCPH by loading precalculated result
        self.BUBBLE = kwargs.get('BUBBLE', None)  #  Calculate bubble correction
        self.RELAX_STR = kwargs.get('RELAX_STR', None)  #  0 Don’t relax the crystal structure (not supported when mode = QHA). 1 Relax atomic positions. 2 Relax both atomic positions and the shape of the unit cell. 3 Lowest-order perturbation theory (not supported when MODE = SCPH).
        
    def get_all_att(self):

        List = vars(self)

        return List

        



#  class for the qha block -> is only neccessary if MODE == QHA
class qha():
    
    def __init__(self, **kwargs):
        
        #  List of all variables that can be set for the qha block input
        #  descriptions taken from ALAMODE webpage
        
        self.KMESH_INTERPOLATE = kwargs.get('KMESH_INTERPOLATE', None)  #  In the iteration process of the SCPH equation, the interpolation is done using the k-mesh defined by KMESH_INTERPOLATE.
        self.KMESH_QHA = kwargs.get('KMESH_QHA', None)  #  This k-mesh is used for the QHA-based structural optimization. Each value of KMESH_QHA must be equal to or a multiple of the number of KMESH_INTERPOLATE in the same direction.
        self.RELAX_STR = kwargs.get('RELAX_STR', None)  #  0 Don’t relax the crystal structure (not supported when mode = QHA). 1 Relax atomic positions. 2 Relax both atomic positions and the shape of the unit cell. 3 Lowest-order perturbation theory (not supported when MODE = SCPH).
        self.LOWER_TEMP = kwargs.get('LOWER_TEMP', None)  #  if 0 SCPH from t_min to t_max, if 1 vice versa
        self.QHA_SCHEME = kwargs.get('QHA_SCHEME', None)  #  0 Full optimization within QHA. 1 zero-static internal stress approximation (ZSISA). 2 volumetric ZSISA (v-ZSISA).
        
    def get_all_att(self):

        List = vars(self)

        return List

        
    


#  class for the &relax block -> is only neccessary if RELAX_STR != 0
class relax():
    
    def __init__(self, **kwargs):
        
        #  List of all variables that can be set for the relax block input
        #  descriptions taken from ALAMODE webpage
        
        self.RELAX_ALGO = kwargs.get('RELAX_ALGO', None)  #  1 for steepest decent, 2 for Newton like method
        self.ALPHA_STDECENT = kwargs.get('ALPHA_STDECENT', None)  #  Coefficient of steepest decent in structural optimization
        self.MAX_STR_ITER = kwargs.get('MAX_STR_ITER', None)  #  Maximum number of structure updates.
        self.ADD_HESS_DIAG = kwargs.get('ADD_HESS_DIAG', None)  #  Correction to the estimated Hessian of free energy in units of kayser
        self.COORD_CONV_TOL = kwargs.get('COORD_CONV_TOL', None)  #  Threshold of convergence for atomic positions in structural
        self.MIXBETA_COORD = kwargs.get('MIXBETA_COORD', None)  #  Mixing coefficient for atomic positions in structure updates.
        self.CELL_CONV_TOL = kwargs.get('CELL_CONV_TOL', None)  #  Threshold of convergence for displacement gradient tensor u_yv in 
        self.MIXBETA_CELL = kwargs.get('MIXBETA_CELL', None)  #  Mixing coefficient for displacement gradient tensor u_yv in structure
        self.SET_INIT_STR = kwargs.get('SET_INIT_STR', None)  #  1 Set initial structure from the input file at each temperature. 2 Start from the crystal structure of the previous temperature. 3 Start from the crystal structure of the previous temperature in low-symmetry phase.
        self.COOLING_U0_INDEX = kwargs.get('COOLING_U0_INDEX', None)  #  0 | 1 | … | 3N-1 (N : the number of atoms in the unit cell)
        self.COOLING_U0_THR = kwargs.get('COOLING_U0_THR', None)  #  Threshold to judge high-symmetry phase in structural optimization [Bohr]
        self.STAT_PRESSURE = kwargs.get('STAT_PRESSURE', None)  #  Hydrostatic pressure in GPa.
        self.RENORM_2TO1ST = kwargs.get('RENORM_2TO1ST', None)  #  0 Set zero. 1 Real-space IFC renormalization. (not recommended) 2 Finite difference method with respect to strain.
        self.RENORM_34TO1ST = kwargs.get('RENORM_34TO1ST', None)  #  0 Set zero. 1 Real-space IFC renormalization.
        self.RENORM_3TO2ND = kwargs.get('RENORM_3TO2ND', None)  #  1 Real-space IFC renormalization. 2 Finite difference method (Read input from all six strain patterns). 3 Finite difference method (Read input from specified strain patterns).
        self.STRAIN_IFC_DIR = kwargs.get('STRAIN_IFC_DIR', None)  #  Directory name of the inputs of strain-IFC couplings.
        
    def get_all_att(self):

        List = vars(self)

        return List


    
    
#  class for the &analysis input block
class analysis():
    
    def __init__(self, **kwargs):
        
        #  List of all variables that can be set for the analysis block input
        #  descriptions taken from ALAMODE webpage
        
        self.GRUNEISEN = kwargs.get('GRUNEISEN', None)  #  Grüneisen parameters will be stored
        self.PRINTEVEC = kwargs.get('PRINTEVEC', None)  #  if 1 Print phonon eigenvectors in the PREFIX.evec file
        self.PRINTXSF = kwargs.get('PRINTXSF', None)  #  if 1 Create an AXSF file PREFIX.axsf
        self.PRINTVEL = kwargs.get('PRINTVEL', None)  #  if 1 Store phonon velocities to a file
        self.PRINTMSD = kwargs.get('PRINTMSD', None)  #  if 1 Save MSD of atoms to the file PREFIX.mds
        self.PDOS = kwargs.get('PDOS', None)  #  if 1 Atom-projected phonon DOS will be stored in PREFIX.dos
        self.TDOS = kwargs.get('TDOS', None)  #  if 1 Two-phonon DOSs will be stored in PREFIX.tdos
        self.SPS = kwargs.get('SPS', None)  #  0 Do not compute scattering phase space 1 Total and mode-decomposed scattering phase space involving the three-phonon processes will be stored in PREFIX.sps 2 Three-phonon scattering phase space with the Bose factor will be stored in PREFIX.sps_Bose
        self.PRINTPR = kwargs.get('PRINTPR', None)  #  if 1 Compute participation ratio and atomic participation ratio, which will be stored in PREFIX.pr and PREFIX.apr respectively.
        self.KAPPA_COHERENT = kwargs.get('KAPPA_COHERENT', None)  #  0 Do not compute the coherent component of thermal conductivity 1 Compute the coherent component of thermal conductivity and save it in PREFIX.kl_coheren. 2 In addition to above (KAPPA_COHERENT = 1), all elements of the coherent term are saved in PREFIX.kc_elem.
        self.KAPPA_SPEC = kwargs.get('KAPPA_SPEC', None)  #  if 1 Compute the thermal conductivity spectra, which will be stored in PREFIX.kappa_spec.
        self.ISOTOPE = kwargs.get('ISOTOPE', None)  #  0 Do not consider phonon-isotope scatterings 1 Consider phonon-isotope scatterings 2 Consider phonon-isotope scatterings as in ISOTOPE = 1 and the calculated selfenergy is stored in PREFIX.gamma_isotope
        self.ISOFACT = kwargs.get('ISOFACT', None)  #  isofact[1], … , isofact[NKD]
        self.UCORR = kwargs.get('UCORR', None)  #  if 1 Compute the displacement-displacement correlation function. The result is stored in PREFIX.ucorr
        self.SHIFT_UCORR = kwargs.get('SHIFT_UCORR', None)  #  This tag specifies the translation vector used for computing the displacement-displacement (uu) correlation function. 
        self.ZMODE = kwargs.get('ZMODE', None)  #  if 1 Compute the mode effective charges of the zone-center phonons. The result is stored in PREFIX.zmode
        self.ANIME = kwargs.get('ANIME', None)  #  This tag is to animate vibrational mode. k1, k2, and k3 specify the momentum of phonon modes to animate, which should be given in units of the reciprocal lattice vector.
        self.ANIME_FRAMES = kwargs.get('ANIME_FRAMES', None)  #  The number of frames saved in animation files
        self.ANIME_CELLSIZE = kwargs.get('ANIME_CELLSIZE', None)  #  This tag specifies the cell size for animation. L1, L2, and L3 should be large enough to be commensurate with the reciprocal point given by the ANIME tag.
        self.ANIME_FORMAT  = kwargs.get('ANIME_FORMAT ', None)  #  When ANIME_FORMAT = xsf, PREFIX.anime???.axsf files are created for XcrySDen. When ANIME_FORMAT = xyz, PREFIX.anime???.xyz files are created for VMD (and any other supporting software such as Jmol).
        
    def get_all_att(self):

        List = vars(self)

        return List

    
    
    
#  function to check if shape of the input is okay (3x3 list of list is required later to create the input)
#  initDisp: 3x3 matrix (as list of list) with initial displacement tensors
def set_strain_block(initDisp):
    
    strainInput = []
    
    row = len(initDisp)
    column = len(initDisp[0])
    
    if row != 3:
        print('Please check number of rows; 3 required %s found'%row)
        print()

    if column != 3:
        print('Please check number of columns; 3 required %s found'%column)
        print()
        
    if row == 3 and column == 3:
        strainInput = initDisp    
    
    return strainInput
    
    
#  function to set the &displace input block
#  dispList: list of lists with displacements
#  DISPMODE: representation of the displacement coordinates
#  compound: relevant if DISPMODE == 0; give an ASE atoms object to get the unit cell of the compound to get the transformation matrix
#  multFactor: multiplication factor for the unit cell; default is 1
def set_displace_block(dispList, DISPMODE, compound = None, multFactor=1, stdIn = 'prim'):
    
    displaceInput = []
    
    #  Fractional coordinate representation
    if DISPMODE == 0:
        displaceInput.append([0])
        if compound != None:
            cell = set_prim_cell_block(compound, multFactor = multFactor, std = stdIn)
            for line in cell:
                displaceInput.append(line)
        
        for line in dispList:
            displaceInput.append(line)
     
    #  Cartesian coordinate representaion
    elif DISPMODE == 1:
        displaceInput.append([1])
        for line in dispList:
            displaceInput.append(line)
            
    else:
        print('Invalid mode selected, please select 0 for fractional coordinates or 1 for cartesian coordinates')
    
    return displaceInput
    
    
#  to get the kpoint input two functions are available to get them via inbuild ASE function or via seeKpath

#  function to get the band path with the build-in functions of ase
#  "contPath" is a boolean that automatically converts dividers ',' in the standard path to a continous path between adjacent, normally broken off, points if TRUE, otherwise path is read in as it is
#  "numCalcPoint" is an int to set how many points should be calculated between two k-points

def path_from_ase_atom(compound, numCalcPoint=250, contPath=False):
    #  get the bravais lattice from primitive cell
    lattice = compound.cell.get_bravais_lattice()
    
    #  get the special points from bravais lattice; dict
    special_points = lattice.get_special_points()
    
    #  get the band path
    ase_path = lattice.bandpath().path    
        
    #  rearange the k-ponits from the special points List for KPMODE = 1 inputs    
    kpointList = []

    
    for key in special_points:
        curPoint = []
        coords = special_points.get(key)
        for coord in coords:
            curPoint.append(coord)
        curPoint.append('# ' + str(key))
        kpointList.append(curPoint)

    k_path = []
    
    for pos, letter in enumerate(ase_path):
        if letter.isalpha() == False:
            if letter.isdigit() == True:
                k_path[-1] += letter 
    
            elif letter == ',':
                k_path.append(letter)
        else:
            k_path.append(letter)



    #  create a list that stores the information in ALAMODE format for the band path that gets returned
    pathInput = []
    
    for pos, point in enumerate(k_path[:-1]):
        line = []
        
        if point != ',' and k_path[pos+1] != ',':
            
            startPoint = special_points.get(point)
            endPoint = special_points.get(k_path[pos+1])
            line.append(point)
            for coord in startPoint:
                line.append(coord)
            line.append(k_path[pos+1])
            for coord in endPoint:
                line.append(coord)
            line.append(numCalcPoint)
            
        elif point == ',' and contPath == True:
            startPoint = special_points.get(k_path[pos-1])
            endPoint = special_points.get(k_path[pos+1])
            line.append(k_path[pos-1])
            for coord in startPoint:
                line.append(coord)
            line.append(k_path[pos+1])
            for coord in endPoint:
                line.append(coord)
            line.append(numCalcPoint)
            
        else:
            continue
        
        pathInput.append(line)

    return pathInput, kpointList


#  function to get band path with seekpath package
#  "contPath" is a boolean that automatically converts jumps in the standard path to a path between adjacent points if TRUE, otherwise path is read in as it is
#  "numCalcPoint" is an int to set how many points should be calculated between two k-points

''' notify user that cif should be standardized, give warning if cif is not standardized, pass as option to create path for original cell

find a way to standardize the the cifs beforehand (maybe via spglib)

 '''

def path_from_seekpath(compound, numCalcPoint=250, contPath=False, numDig=6):
    pathInput = []
    
    #  create fractional coordinates from ase atoms object
    fracCoord_pc = compound.get_scaled_positions()
    # for atom in compound.positions:
    #     fracAtom = []
    #     for num, coord in enumerate(atom):
    #         fracAtom.append(round(coord/compound.cell[num][num], 6))
    #     fracCoord_pc.append(fracAtom)    
    
    #  use seekpath 
    path = seekpath.get_path((compound.cell, fracCoord_pc, compound.numbers))
    point_coords = path.get('point_coords') #  type: dict class
    k_path = path.get('path') #  type: simple List object
    
    #  rearange the k-ponits from the special points List for KPMODE = 1 inputs    
    kpointList = []

    
    for key in point_coords:
        curPoint = []
        coords = point_coords.get(key)
        for coord in coords:
            curPoint.append(round(coord, numDig))
        curPoint.append('# ' + str(key))
        kpointList.append(curPoint)

        
    #  create the path as a List already formatted for alamode
    for pos, point in enumerate(k_path):
        line = []
        if pos < len(k_path)-1:  #  To add a path between two path fragments in case the plot should look nicer/there are problems with non-continuous paths
            if point[1] != k_path[pos+1][0] and contPath == True:
                k_path.insert(pos+1, (point[1], k_path[pos+1][0]))
            
        startPoint = point[0]
        endPoint = point[1]
        for key in point_coords:
            if key == startPoint:
                line.append(str(key))
                coords = point_coords.get(key)
                for coord in coords:
                    line.append(round(coord, numDig))
                continue
            
        for key in point_coords:
            if key == endPoint:
                line.append(str(key))
                coords = point_coords.get(key)
                for coord in coords:
                    line.append(round(coord, numDig))
                    
        line.append(numCalcPoint)            
        pathInput.append(line)

    return pathInput, kpointList


#  function to set get input for the &kpoint block
#  compound: ASE atoms object of the analyzed compound
#  kpointSource: source of the method to obtain the k-points (up to this point ase inbuild methods and seeKpath are supported); "ase" set as default since seeKpath might not be installed
#  KPMODE: ALAMODE attribute of the &kpoint field, will generate appropriate input list for each case 0, 1, 2
#  numCalcPoint: relevant for KPMODE == 1; will set the number of points to be along a path between two k-points; default of 250 points
#  contPath: relevant for KPMODE == 1; boolean; set True if the k-path should be continous e.g. Γ—X—M—Γ—R—X|R—M is set to Γ—X—M—Γ—R—X-R—M
#  DOS_kgrid: relevant for KPMODE == 2; sets the k-grid for DOS calculations; default is 20 (not sure if that value is any good though)

def set_kpoint_block(compound, kpointSource='ase', KPMODE=1, numCalcPoint=250, contPath=False, DOS_kgrid=20):
    
    kpointBlock = []
    
    #  get the k-point coordinates and the path from selected source (ase is default, since seekpath might not be installed by default)
    if kpointSource == 'ase':
        pathInput, kpointList = path_from_ase_atom(compound, numCalcPoint=numCalcPoint, contPath=contPath)
    elif kpointSource == 'seekpath':
        pathInput, kpointList = path_from_seekpath(compound, numCalcPoint=numCalcPoint, contPath=contPath)
    else:
        print('Invalid k-point source selected, please select "ase" or "seekpath"!')
        pathInput = []
        kpointList= []
    
    
    
    if KPMODE == 0:  #  Calculate phonon frequencies at given k-points
        kpointBlock.append([0])
        
        for line in kpointList:
            kpointBlock.append(line)
        
    elif KPMODE == 1:  #  Band dispersion calculation
        kpointBlock.append([1])
        
        for line in pathInput:
            kpointBlock.append(line)
        
    elif KPMODE == 2:  #  Uniform k grid for phonon DOS and thermal conductivity
        kpointBlock.append([2])
        
        kpointBlock.append([DOS_kgrid, DOS_kgrid, DOS_kgrid])
    
    
    return kpointBlock


  #  this functions writes an ANPHON input based on one ASE atoms object
  #  by default it adds the &cell and &kpoint based on the passed attributes and object

def write_ANPHON_input(aseAtom, generalInput=None, scphInput=None, qhaInput=None, relaxInput=None, strainInput=None, displaceInput=None, DISPMODE=None, analysisInput=None, multFactor=1, fileName='', source='ase', KPMODE=1, numCalcPoint=250, contPath=False, DOS_kgrid=20, stdIn = 'prim', **kwargs):
    
    #  function that writes the ANPHON input based on one ASE atoms object and instances of the general and interaction class, that hold the corresponding keywords for the calculation
    #  optional possibility to set a filename
    

    
    if fileName != '' and fileName.endswith('.in'):
        ANPHONinput = fileName
    elif fileName != '' and fileName.endswith('.in') == False:
        ANPHONinput = fileName + '.in'
    else:
        ANPHONinput = 'ANPHONinput.in'
        
    with open(ANPHONinput, 'w') as file:
        
        if generalInput != None:
            file.write('&general\n')
            
            #  get all overview of all attributes of the general object
            generalCom = generalInput.get_all_att()
    
            #  iterate over all attributes of the general object, only consider those that were set (thus are not NONE), get their value and print it
            for com in generalCom:
                if generalCom.get(com) != None:
                    file.write(' ' + com + ' = ')
                    
                    if type(generalCom.get(com)) == list:
                        for val in generalCom.get(com):
                            file.write(str(val) + ' ')
                    else:
                        file.write(str(generalCom.get(com)))
                    file.write('\n')
                    
            file.write('/\n\n\n')
        
        
        if scphInput != None:
            file.write('&scph\n')
            
            scphCom = scphInput.get_all_att()
            
            for com in scphCom:
                if scphCom.get(com) != None:
                    file.write(' ' + com + ' = ')
                    
                    if type(scphCom.get(com)) == list:
                        for val in scphCom.get(com):
                            file.write(str(val) + ' ')
                    else:
                        file.write(str(scphCom.get(com)))
                    file.write('\n')
            
            file.write('/\n\n\n')
            
            
        if qhaInput != None:
            file.write('&qha\n')
            
            qhaCom = qhaInput.get_all_att()
            
            for com in qhaCom:
                if qhaCom.get(com) != None:
                    file.write(' ' + com + ' = ')
                    
                    if type(qhaCom.get(com)) == list:
                        for val in qhaCom.get(com):
                            file.write(str(val) + ' ')
                    else:
                        file.write(str(qhaCom.get(com)))
                    file.write('\n')
            
            file.write('/\n\n\n')
        
        
        if relaxInput != None:
            file.write('&relax\n')
            
            relaxCom = relaxInput.get_all_att()
            
            for com in relaxCom:
                if relaxCom.get(com) != None:
                    file.write(' ' + com + ' = ')
                    
                    if type(relaxCom.get(com)) == list:
                        for val in relaxCom.get(com):
                            file.write(str(val) + ' ')
                    else:
                        file.write(str(relaxCom.get(com)))
                    file.write('\n')
            
            file.write('/\n\n\n')
            
        
        file.write('&cell\n')
        cellInput = set_prim_cell_block(aseAtom, multFactor=multFactor, std = stdIn)
        
        for line in cellInput:
            file.write(' ')
            for el in line:
                file.write(str(el) + ' ')
            file.write('\n')
        
        file.write('/\n\n\n')
        
        
        file.write('&kpoint\n')
        kpointInput = set_kpoint_block(aseAtom, kpointSource=source, KPMODE=KPMODE, numCalcPoint=numCalcPoint, contPath=contPath, DOS_kgrid=DOS_kgrid)
        
        for line in kpointInput:
            file.write(' ')
            for el in line:
                file.write(str(el) + ' ')
            file.write('\n')
        
        file.write('/\n\n\n')
        
        
        if strainInput != None:
            file.write('&strain\n')
            
            strainIn = set_strain_block(strainInput)
            
            for line in strainIn:
                file.write(' ')
                for el in line:
                    file.write(str(el) + ' ')
                file.write('\n')
            
            file.write('/\n\n\n')
            
        
        if displaceInput != None:
            file.write('&displace\n')
            
            dispIn = set_displace_block(displaceInput, DISPMODE, compound=aseAtom)
            
            for line in dispIn:
                file.write(' ')
                for el in line:
                    file.write(str(el) + ' ')
                file.write('\n')
            
            file.write('/\n\n\n')
            
            
        if analysisInput != None:
            file.write('&analysis\n')
            
            analysisCom = analysisInput.get_all_att()
            
            for com in analysisCom:
                if analysisCom.get(com) != None:
                    file.write(' ' + com + ' = ')
                    
                    if type(analysisCom.get(com)) == list:
                        for val in analysisCom.get(com):
                            file.write(str(val) + ' ')
                    else:
                        file.write(str(analysisCom.get(com)))
                    file.write('\n')
            
            file.write('/\n\n\n')
        
        file.close()

        
    print('ANPHON input saved as %s\n'%ANPHONinput)
    
    return




#  script to create phonon bands and SCPH phonon bands ANPHON inputs.

if __name__ == '__main__':
    
    print(r'/\___/\ ')
    print(r':O: :O:   Script to create ANPHON.in input-files from cif-files.')
    print(r' ¨   ¨')

    
    """
    
    This script is designed for our use, so if other parameters are needed or other workflows are used, please customize the script or just import the classes to write own file

    variables to be set by the user:
        step -> select whether phonons or SCPH should be calculated (gives default for filename, but changable with -fn)
        optional:
            cif  -> cif-file with (optimized) crystal structure, this will also store the cell and supercell as pickle objects, so setting the cif file is only neccesary for the first step
            fn  -> file-name of the output
            p   -> prefix to add to created files by ALAMODE
            fcs -> set file-name for FCSXML attribute
            s   -> set the source of the k-path (ase or seekpath)
            cp  -> set the k-path to continous e.g. Γ—X—M—Γ—R—X|R—M is changed to Γ—X—M—Γ—R—X-R—M (default is "false")
            kpm -> set the value for KPMODE (default is 1)
    """
    
    parser = argparse.ArgumentParser(description='Wizard to create ANPHON inputs from cif files', formatter_class=argparse.RawTextHelpFormatter, epilog='Additional keywords of ANPHON variables can be given, they will be added to the right blocks automatically.')
        
    parser.add_argument("step", help='set the step of the calculation\n' + 
                    'phonons: create phband.in with default parameters\n' + 
                    'SCPH: create scph.in with default parameters\n', type=str, choices=['phonons', 'SCPH'])
    
    parser.add_argument("-cif", help="CIF-file from which the structure is read, saves the unit cell and created supercell using json; If not set cell is loaded if available", nargs='?', default='', type=str)

    parser.add_argument("-fn", "--FNAME", help="set the name of the created file", nargs='?', default='', type=str)
    
    parser.add_argument("-p", "--PREFIX", nargs='?', type=str, help="set the prefix for ALM output files", default='prefix')
    
    parser.add_argument("-fcs", "--FCSXML", help='xml file with stored force constants', nargs='?', type=str, default='')
    
    parser.add_argument("-s", "--SOURCE", help='choose the source for calculating the k-points, currently "ase" and "seekpath" are available', choices=['ase', 'seekpath'], type=str, default='seekpath')
    
    parser.add_argument("-cp", "--CONTPATH", help='option to set the given k-path to continous, so every jump between points is replaced by a direct path between the adjacent k-points', type=bool, default=False)
    
    parser.add_argument("-kpm", "--KPMODE", help='set the KPMODE (default is 1)', type=int, default=1)

    parser.add_argument("-temp", "--TEMPLATE", help="give a template that includes additional arguments, they will be added to the corresponding blocks (&block arguments are ignored, but can be included for better fromating of the template)", nargs='?', type=str, default='')

    
    #  parse the arguments and save all unknown attributes in a dictionary that gets passed to the instances of the objects
    args, unknown = parser.parse_known_args()
    kwargs = process_additional_arguments(unknown)
        
    ###########################################################################
    
    #  get possible additional keywords from a template (change name to variable)
    if args.TEMPLATE != '':
        add_keys = get_keywords_from_template(args.TEMPLATE)
        kwargs = add_keys | kwargs


    #  check if a cif is set and create aseAtoms objects from that cif
    #  if left empty, search for saved ase atoms objects in directory; exit the script if no objects are found

    if args.cif != '':
        cifIn = args.cif
        compound = cif.read_cif(cifIn)
        #pickle.dump(compound, open('cell', 'wb'), pickle.HIGHEST_PROTOCOL)
        write_json(open('cell', 'w'), compound)  #  save normal cell ase Atoms object

    
    else:        
        try:
            compound = read_json(open('cell', 'r'))
            #compound_sc = pickle.load(open('supercell', 'rb'))
            print('Cell loaded from previous step.\n')
        
        except FileNotFoundError:
            print('No saved cell and/or supercell found.\n')
            print('Please rerun script with -cif option set!')
            sys.exit()
        
        

        #  This block defines the instances of the classes with which the general, scph, qha, realx and analysis block are generated. Change this if other defaults are needed.
        #  The step parameter sets the calculation step
            #  phonons -> calculate the phonon band structure
            #  scph    -> calculate the self consistent phonon band structure
        
        #  In the future it should be possible to give a template for the commands to set in the each block

    if args.step == 'phonons':
        print('Mode %s selected.'%args.step)
        print()
        
        if args.FNAME == '':
            args.FNAME = 'phband.in'

        
        if args.FCSXML == '':
            print('Searching for file with harmonic terms in directory.\n')
            
            FCS2, FCS3, FCS4 = get_fcsXML(fcs2=True)
            args.FCSXML = FCS2        
            
        generalIn = ANPHONgeneral(compound, PREFIX = args.PREFIX, MODE=args.step, FCSXML=args.FCSXML, **kwargs)
        
          #  This block checks if keywords for &qha, &relax and &analysis are given. If so the corresponding objects will be passed to the write_ANPHON_input() function
          
        scphInput = scph(**kwargs)
        scphList = scphInput.get_all_att()
        oneSCPHset = False
          
        qhaInput = qha(**kwargs)
        qhaList = qhaInput.get_all_att()
        oneQHAset = False
                
        relaxInput = relax(**kwargs)
        relaxList = relaxInput.get_all_att()
        oneRELAXset = False
                
        analysisInput = analysis(**kwargs)
        analysisList = analysisInput.get_all_att()
        oneANALYSISset = False
        
        
        #  collect all items in Lists to loop through
        boolList = [oneSCPHset, oneQHAset, oneRELAXset, oneANALYSISset]
        inList = [scphInput, qhaInput, relaxInput, analysisInput]
        inListList = [scphList, qhaList, relaxList, analysisList]
        inListSTR = ['scphInput', 'qhaInput', 'relaxInput', 'analysisInput']
        
        
        addBlocks = {}  #  This dict object will be passed to the write_ANPHON_input function as a dictionary, possibly containing additional objects of the input block classes
       
        for num, obj in enumerate(inList):
            List = inListList[num]
            for key in List:  #  This will check if any of the block objects has a non NONE value, so check if any of the variables was called during running the script
                if List.get(key) != None:
                    boolList[num] = True
            if boolList[num] == True:  #  if any block needs to be added due to a set variable, it will be added to the **addBlocks dict
                addBlocks[inListSTR[num]] = inList[num]
 
    
        write_ANPHON_input(compound, generalInput=generalIn, fileName=args.FNAME, Source=args.SOURCE, KPMODE=args.KPMODE, contPath=args.CONTPATH, **addBlocks)
        
        
    elif args.step == 'SCPH':
        print('Mode %s selected'%args.step)
        print()
        
        if args.FNAME == '':
            args.FNAME = 'scph.in'

        
        if args.FCSXML == '':
            print('Searching for file with quartic terms in directory.\n')
            
            FCS2, FCS3, FCS4 = get_fcsXML(fcs4=True)
            args.FCSXML = FCS4        

        
        generalIn = ANPHONgeneral(compound, PREFIX = args.PREFIX, MODE=args.step, FCSXML=args.FCSXML, DT=50, **kwargs)
        
        scphIn = scph(SELF_OFFDIAG = 0, MAXITER = 1000, MIXALPHA = 0.1, KMESH_INTERPOLATE = [4, 4, 4], KMESH_SCPH = [8, 8, 8], LOWER_TEMP = 1, **kwargs)
        
        write_ANPHON_input(compound, generalInput=generalIn, scphInput=scphIn, fileName=args.FNAME, Source=args.SOURCE, KPMODE=args.KPMODE, contPath=args.CONTPATH)
        
    else:    
        print('Invalid step selected, please select "phonons" or "scph')
        print()
    
    
    


    
    
    
    print()
    print()  
    print(r'      /\       /\ ')
    print(r'     /  \_____/  \      .')
    print(r'    . :::     ::: .    .:.')
    print(r'   : ::O::: :::O:: :  .:::.')
    print(r'   :  :::  o  :::  : .......')
    print('   mmm          mmm   ..... ')
    print('---------------------------------')
    print('FINISHED')



"""
    modify scripts to read Templates (for later to use for screening/modifying stuff)
      
    test script for all 4 phases of BaTiO3 -> see how inputs work
     
    run the workflow from Kim with an optimized SrTiO3 cif file to see if dispersions look the same (currently witing to calculating the ALM0 displaced cells)


   notify user that cif should be standardized, give warning if cif is not standardized
   
   -> have a look whether ase/seeKpath normalize the cell -> if not pass as option to create path for original cell or additional step to sy´andardize a cell

    find a way to standardize the the cifs beforehand (maybe via spglib)
    -> write a function for that, maybe one that also gives back a standardized cif-file ...
    
    -> see if function of ase get_scaled_position is usefull




"""

























